Repository Jaeyong-seo/Congratulation_Cake, pull requests merged in 2023-02, with the labels that each got.

#1 chore: install eslint and prettier and code formatting
  client/.eslintrc.js
  client/.eslintrc.json
  client/.prettierrc.js
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/api/hello.ts
  client/src/pages/index.tsx
  client/src/styles/Home.module.css
  client/src/styles/globals.css
  client/yarn.lock
Labels: chore

#2 feat: add basic routing
  client/.eslintrc.js
  client/src/pages/_app.tsx
  client/src/pages/api/hello.ts
  client/src/pages/cake/index.tsx
  client/src/pages/create/index.tsx
  client/src/pages/index.tsx
  client/src/styles/Home.module.css
  client/src/styles/globals.css
Labels: feat

#4 feat: add mui(with styled-component) and add style example
  client/package-lock.json
  client/package.json
  client/src/component/NewButton/index.tsx
  client/src/component/NewButton/styles.ts
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/index.tsx
  client/styles/theme.tsx
  client/util/creationEmotionCache.js
  client/yarn.lock
Labels: feat

#6 feat: add password validation
  client/src/pages/create/index.tsx
Labels: feat

#7 feat: modify favicon and title
  client/public/favicon.ico
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
Labels: feat

#9 feat: implement home page with responsive layout
  client/src/asset/images/Celebrate.png
  client/src/asset/images/MainHeart.png
  client/src/component/Button/index.tsx
  client/src/component/Button/styles.ts
  client/src/component/HomePage/index.tsx
  client/src/component/HomePage/styles.ts
  client/src/component/LinkText/index.tsx
  client/src/component/LinkText/styles.ts
  client/src/component/MainBlock/index.tsx
  client/src/component/MainBlock/styles.ts
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/styles/theme.tsx
  client/yarn.lock
Labels: feat

#11 chore: add local font for initial set up
  client/.eslintrc.js
  client/package.json
  client/public/fonts/SCDream1.otf
  client/src/component/Button/styles.ts
  client/src/component/FontGroup/index.tsx
  client/src/pages/_app.tsx
  client/yarn.lock
Labels: chore

#12 chore: add api call feature using swr and axios
  .gitignore
  client/.env.template
  client/package.json
  client/src/apis/get/getCake.ts
  client/src/constant/api.ts
  client/src/pages/_app.tsx
  client/src/pages/cake/[id]/index.tsx
  client/yarn.lock
Labels: feat, chore

#13 feat: cake pages and basic components
  client/src/asset/images/celebrate_text.png
  client/src/component/Card/index.tsx
  client/src/component/Card/styles.ts
  client/src/component/CelebratePage/index.tsx
  client/src/component/CelebratePage/styles.ts
  client/src/component/CommonBackground/index.tsx
  client/src/component/CommonBackground/styles.ts
  client/src/pages/cake/[id]/celebrate.tsx
  client/src/pages/cake/[id]/edit.tsx
  client/src/pages/cake/[id]/index.tsx
  client/src/pages/cake/hello.tsx
Labels: feat

#15 feat: edit cakes flow
  client/src/component/Atoms/Button/index.tsx
  client/src/component/Atoms/Button/styles.ts
  client/src/component/Atoms/CakeSelector/index.tsx
  client/src/component/Atoms/CakeSelector/styles.ts
  client/src/component/Atoms/Calendar/index.tsx
  client/src/component/Atoms/Calendar/styles.ts
  client/src/component/Atoms/Card/index.tsx
  client/src/component/Atoms/Card/styles.ts
  client/src/component/Atoms/CreateForms/CakeForm.tsx
  client/src/component/Atoms/CreateForms/DateForm.tsx
  client/src/component/Atoms/CreateForms/NameForm.tsx
  client/src/component/Atoms/CreateForms/PasswordForm.tsx
  client/src/component/Atoms/CreateForms/TopperForm.tsx
  client/src/component/Atoms/InputBox/index.tsx
  client/src/component/Atoms/InputBox/styles.ts
  client/src/component/Atoms/InputPw/index.tsx
  client/src/component/Atoms/InputPw/styles.ts
  client/src/component/Atoms/LinkButton/index.tsx
  client/src/component/Atoms/LinkButton/styles.ts
  client/src/component/Atoms/LinkText/index.tsx
  client/src/component/Atoms/LinkText/styles.ts
  client/src/component/Atoms/PrevButton/index.tsx
  client/src/component/Atoms/PrevButton/styles.ts
  client/src/component/Atoms/PreviewCakes/CompleteCake.tsx
  client/src/component/Atoms/PreviewCakes/WaitCake.tsx
  client/src/component/Button/index.tsx
  client/src/component/Common/CommonBackground/index.tsx
  client/src/component/Common/CommonBackground/styles.ts
  client/src/component/Common/FontGroup/index.tsx
  client/src/component/Common/MainBlock/index.tsx
  client/src/component/Common/MainBlock/styles.ts
  client/src/component/CreateForms/NameForm.tsx
  client/src/component/CreateForms/PasswordForm.tsx
  client/src/component/NewButton/index.tsx
  client/src/component/NewButton/styles.ts
  client/src/component/Page/CelebratePage/index.tsx
  client/src/component/Page/CelebratePage/styles.ts
  client/src/component/Page/CreatePage/index.tsx
  client/src/component/Page/CreatePage/styles.ts
  client/src/component/Page/HomePage/index.tsx
  client/src/component/Page/HomePage/styles.ts
  client/src/pages/_app.tsx
  client/src/pages/cake/[id]/celebrate.tsx
  client/src/pages/cake/[id]/edit.tsx
  client/src/pages/cake/[id]/index.tsx
  client/src/pages/create/index.tsx
  client/src/pages/index.tsx
Labels: feat

#16 feat: add celebrate flow
  client/src/component/Atoms/Forms/CakeForm.tsx
  client/src/component/Atoms/Forms/DateForm.tsx
  client/src/component/Atoms/Forms/ImageForm.tsx
  client/src/component/Atoms/Forms/MessageForm.tsx
  client/src/component/Atoms/Forms/NameForm.tsx
  client/src/component/Atoms/Forms/PasswordForm.tsx
  client/src/component/Atoms/Forms/TopperForm.tsx
  client/src/component/Atoms/PreviewCakes/CelebrateCompleteCake.tsx
  client/src/component/Atoms/PreviewCakes/EditCompleteCake.tsx
  client/src/component/Page/CreatePage/index.tsx
  client/src/pages/cake/[id]/celebrate.tsx
  client/src/pages/cake/[id]/edit.tsx
Labels: feat

#18 feat: add congratulation-flow
  client/src/asset/images/congratulation_text.png
  client/src/component/Page/CakePage/index.tsx
  client/src/component/Page/CakePage/styles.ts
  client/src/component/Page/CongratulationPage/index.tsx
  client/src/component/Page/CongratulationPage/styles.ts
  client/src/pages/cake/[id]/celebrate.tsx
  client/src/pages/cake/[id]/congratulation.tsx
  client/src/pages/cake/[id]/index.tsx
Labels: feat

#20 feat: api-test
  client/src/apis/get/getCake.ts
  client/src/pages/cake/[id]/index.tsx
Labels: chore

#21 feat: api request test
  client/src/apis/get/getCake.ts
  client/src/apis/get/getMessages.ts
  client/src/apis/get/getPwConfirm.ts
  client/src/component/Atoms/Forms/CakeForm.tsx
  client/src/component/Atoms/Forms/ImageForm.tsx
  client/src/component/Atoms/Forms/WritterForm.tsx
  client/src/component/Atoms/Forms/styles.ts
  client/src/component/Page/CakePage/index.tsx
  client/src/component/Page/CelebratePage/index.tsx
  client/src/component/Page/CreatePage/index.tsx
  client/src/pages/cake/[id]/celebrate.tsx
  client/src/pages/cake/[id]/congratulation.tsx
  client/src/pages/cake/[id]/edit.tsx
Labels: feat
